# Copyright (C) 2023-24 demarcush
# License: AGPL-3.0-or-later (https://www.gnu.org/licenses/agpl.txt)
# Repository: https://github.com/demarcush/breakfree
## Software: Clash Meta
## Country: Iran

p: &p {type: "http", interval: 86400, health-check: {enable: true, interval: 3600, lazy: true, url: "https://youtu.be/robots.txt", expected-status: 200}}
mixed-port: 7890
allow-lan: true
bind-address: '*'
udp: true
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
dns:
    enable: true
    ipv6: true
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback: ['https://doh.dns.sb/dns-query', 'https://dns.cloudflare.com/dns-query', 'https://120.53.53.53/dns-query', dot.pub]
    fallback-filter: { geo: [240.0.0.0/4, 0.0.0.0/32] }

proxy-groups:

- name: default
  type: select
  proxies:
    - auto
    - manual
    - DIRECT
    - REJECT

- name: manual
  type: select
  include-all-providers: true

- name: auto
  type: url-test
  #filter: "🏁|🏴‍☠️|🚩"
  hidden: true
  include-all-providers: true

proxy-providers:

  dvd:
    url: "https://raw.githubusercontent.com/abbasdvd3/clash/main/GeoIP/hysteria2"
    path: "./providers/dvd.yaml"
    <<: *p
rule-providers:

  ir:
    type: http
    format: text
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Chocolate4U/Iran-clash-rules@release/ir.txt"
    path: ./ruleset/ir.txt
    interval: 86400

  ircidr:
    type: http
    format: text
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Chocolate4U/Iran-clash-rules@release/ircidr.txt"
    path: ./ruleset/ircidr.txt
    interval: 86400

  apps:
    type: http
    format: text
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Chocolate4U/Iran-clash-rules@release/apps.txt"
    path: ./ruleset/apps.txt
    interval: 86400

  category-ads-all:
    type: http
    format: text
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Chocolate4U/Iran-clash-rules@release/category-ads-all.txt"
    path: ./ruleset/category-ads-all.txt
    interval: 86400

  cryptominers:
    type: http
    format: text
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Chocolate4U/Iran-clash-rules@release/cryptominers.txt"
    path: ./ruleset/cryptominers.txt
    interval: 86400

  malware:
    type: http
    format: text
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Chocolate4U/Iran-clash-rules@release/malware.txt"
    path: ./ruleset/malware.txt
    interval: 86400

  malware-ip:
    type: http
    format: text
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Chocolate4U/Iran-clash-rules@release/malware-ip.txt"
    path: ./ruleset/malware-ip.txt
    interval: 86400

  nsfw:
    type: http
    format: text
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Chocolate4U/Iran-clash-rules@release/nsfw.txt"
    path: ./ruleset/nsfw.txt
    interval: 86400

  phishing:
    type: http
    format: text
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Chocolate4U/Iran-clash-rules@release/phishing.txt"
    path: ./ruleset/phishing.txt
    interval: 86400

  phishing-ip:
    type: http
    format: text
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Chocolate4U/Iran-clash-rules@release/phishing-ip.txt"
    path: ./ruleset/phishing-ip.txt
    interval: 86400

rules:
  - OR,((GEOSITE,private),(GEOIP,private,no-resolve),(RULE-SET,apps)),DIRECT

  - OR,((RULE-SET,category-ads-all),(RULE-SET,malware),(RULE-SET,phishing),(RULE-SET,cryptominers)),REJECT
  #- RULE-SET,nsfw,REJECT ## Pornography and gambling

  - RULE-SET,ir,DIRECT
  - OR,((DOMAIN-SUFFIX,d.metacubex.one),(DOMAIN-SUFFIX,yacd.haishan.me)),DIRECT ## Dashboards
  #- GEOSITE,category-games,DIRECT ## Gaming

  - GEOSITE,geolocation-!cn,default ## When all else failed, vote from the rooftops.

  - OR,((RULE-SET,malware-ip),(RULE-SET,phishing-ip)),REJECT
  - RULE-SET,ircidr,DIRECT

  - MATCH,default
