# Copyright (C) 2023-24 demarcush
# License: AGPL-3.0-or-later (https://www.gnu.org/licenses/agpl.txt)
# Repository: https://github.com/demarcush/breakfree
## Software: Clash Meta
## Country: Iran

p: &p {type: "http", interval: 86400, health-check: {enable: true, interval: 3600, lazy: true, url: "https://youtu.be/robots.txt", expected-status: 200}}
mixed-port: 7890
allow-lan: true
bind-address: '*'
udp: true
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
dns:
  enable: false
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.local'
    - 'localhost.ptlogin2.qq.com'
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.microsoft.com'
    - '+.xboxlive.com'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
    - '*.lan'
    - 'speedtest.cros.wr.pvp.net'
  use-hosts: false
  use-system-hosts: true
  respect-rules: true
  default-nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  proxy-server-nameserver:
    - https://doh.pub/dns-query
  direct-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

proxy-groups:

- name: default
  type: select
  proxies:
    - auto
    - manual


- name: manual
  type: select
  include-all-providers: true

- name: auto
  type: url-test
  #filter: "🏁|🏴‍☠️|🚩"
  hidden: true
  include-all-providers: true
- name: 🎯
  type: select
  proxies:
    - DIRECT
    - default
    

proxy-providers:
   
  dvd:
    url: "https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml"
    <<: *p

rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: yaml}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: yaml}
rule-providers:
  private_domain:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.yaml
  ehentai_domain:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ehentai.yaml
  github_domain:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.yaml
  twitter_domain:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.yaml
  youtube_domain:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.yaml
  google_domain:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.yaml
  telegram_domain:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.yaml
  netflix_domain:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.yaml
  pixiv_domain:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/pixiv.yaml
  geolocation-!cn:
    <<: *domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.yaml

  private_ip:
    <<: *ip
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.yaml
  cn_ip:
    <<: *ip
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.yaml
  google_ip:
    <<: *ip
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.yaml
  netflix_ip:
    <<: *ip
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.yaml
  twitter_ip:
    <<: *ip
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/twitter.yaml
  telegram_ip:
    <<: *ip
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.yaml
  block:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    interval: 86400
  AWA:
    type: http
    behavior: domain
    format: yaml
    url: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.yaml
    interval: 86400
  ir:
    type: http
    format: yaml
    behavior: domain
    url: https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ir.yaml
    interval: 86400
  ads:
    type: http
    format: yaml
    behavior: domain
    url: https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ads.yaml
    interval: 86400
  malware:
    type: http
    format: yaml
    behavior: domain
    url: https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/malware.yaml
    interval: 86400
  phishing:
    type: http
    format: yaml
    behavior: domain
    url: https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/phishing.yaml
    interval: 86400
  cryptominers:
    type: http
    format: yaml
    behavior: domain
    url: https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/cryptominers.yaml
    interval: 86400
  apps:
    type: http
    format: yaml
    behavior: classical
    url: https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/apps.yaml
    interval: 86400
  ircidr:
    type: http
    format: yaml
    behavior: ipcidr
    url: https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ircidr.yaml
    interval: 86400
  private:
    type: http
    format: yaml
    behavior: ipcidr
    url: https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/private.yaml
    interval: 86400
  irasn:
    type: http
    format: yaml
    behavior: classical
    url: https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/irasn.yaml
    interval: 86400
  Google:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/mphin/ProxyTools/main/rules/Google.list
    format: text
    interval: 86400
  IpinfoSpeedtest:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/mphin/ProxyTools/main/rules/IpinfoSpeedtest.list
    format: text
    interval: 86400
  gfw:
    type: http
    format: yaml
    behavior: domain
    url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
    interval: 86400
  UnBan:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
    format: text
    interval: 86400
  BanAD:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
    format: text
    interval: 86400
  BanProgramAD:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
    format: text
    interval: 86400
  BanEasyList:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
    format: text
    interval: 86400
  BanEasyListChina:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
    format: text
    interval: 86400
  BanEasyPrivacy:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
    format: text
    interval: 86400 
  GoogleFCM:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
    format: text
    interval: 86400
  GoogleCN:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
    format: text
    interval: 86400
  SteamCN:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
    format: text
    interval: 86400
  Bing:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
    format: text
    interval: 86400
  OneDrive:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
    format: text
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
    format: text
    interval: 86400
  Apple:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
    format: text
    interval: 86400
  Telegram:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
    format: text
    interval: 86400
  OpenAi:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
    format: text
    interval: 86400
  NetEaseMusic:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
    format: text
    interval: 86400
  Epic:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
    format: text
    interval: 86400
  Origin:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
    format: text
    interval: 86400
  Sony:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
    format: text
    interval: 86400
  Steam:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
    format: text
    interval: 86400
  Nintendo:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
    format: text
    interval: 86400
  YouTube:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
    format: text
    interval: 86400
  Netflix:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
    format: text
    interval: 86400
  Bahamut:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
    format: text
    interval: 86400
  BilibiliHMT:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
    format: text
    interval: 86400
  Bilibili:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
    format: text
    interval: 86400
  ChinaMedia:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
    format: text
    interval: 86400
  ProxyMedia:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
    format: text
    interval: 86400
  ProxyGFWlist:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
    format: text
    interval: 86400
  ChinaDomain:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
    format: text
    interval: 86400
  ChinaCompanyIp:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
    format: text
    interval: 86400
  Download:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
    format: text
    interval: 86400
  GoogleCNProxyIP:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleCNProxyIP.list
    format: text
    interval: 86400
  DNS:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/DNS/DNS.yaml
    format: text
    interval: 86400
  GitHub:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/GitHub/GitHub.yaml
    format: text
    interval: 86400
  AdGuardSDNSFilter:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/AdGuardSDNSFilter/AdGuardSDNSFilter_Domain.txt
    format: text
    interval: 86400
  BlockHttpDNS:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/BlockHttpDNS/BlockHttpDNS.yaml
    format: text
    interval: 86400
  AdGuardSDNSFilterDirect:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/AdGuardSDNSFilter/Direct/Direct.yaml
    format: text
    interval: 86400
  Samsung:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/Samsung/Samsung.yaml
    format: text
    interval: 86400
  ChinaDNS:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/release/rule/Clash/ChinaDNS/ChinaDNS.yaml
    format: text
    interval: 86400
  cloudflare:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo-lite/geosite/cloudflare.list
    format: text
    interval: 86400
  Domestic:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/LM-Firefly/Rules/master/Domestic.list
    format: text
    interval: 86400
  Adblock1:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/LM-Firefly/Rules/master/Adblock/Adblock.list
    format: text
    interval: 86400
  DNS2:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/LM-Firefly/Rules/master/Special/DNS.list
    format: text
    interval: 86400
  category-ads-all:
    type: http
    format: yaml
    behavior: domain
    url: https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/category-ads-all.yaml
    interval: 86400
  nsfw1:
    type: http
    format: yaml
    behavior: domain
    url: https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/nsfw.yaml
    interval: 86400
  social:
    type: http
    format: yaml
    behavior: domain
    url: https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/social.yaml
    interval: 86400
  Google1:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Google.list
    format: text
    interval: 86400   
  LocalAreaNetwork:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
    format: text
    interval: 86400
  SpeedTest:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/LM-Firefly/Rules/master/SpeedTest.list
    format: text
    interval: 86400
  NSFW:  
    type: http  
    behavior: classical
    url: https://raw.githubusercontent.com/tanmoumou252/NSFW-website-rule-for-Clash/main/NSFW.yaml
    format: yaml
    interval: 86400
rules:
  - RULE-SET,private_ip,🎯,no-resolve
  - RULE-SET,github_domain,🕹 select
  - RULE-SET,twitter_domain,default
  - RULE-SET,youtube_domain,default
  - RULE-SET,google_domain,default
  - RULE-SET,telegram_domain,default
  - RULE-SET,netflix_domain,default
  - RULE-SET,geolocation-!cn,default

  - RULE-SET,google_ip,default
  - RULE-SET,netflix_ip,default
  - RULE-SET,telegram_ip,default
  - RULE-SET,twitter_ip,default

  - RULE-SET,LocalAreaNetwork,🎯
  - RULE-SET,private,🎯,no-resolve
  - RULE-SET,apps,🎯
  - RULE-SET,UnBan,🎯
  - RULE-SET,ir,🎯
  - RULE-SET,ircidr,🎯
  - RULE-SET,irasn,🎯
  - GEOIP,google,default
#  - GEOIP,microsoft,Ⓜ️
#  - GEOIP,bing,Ⓜ️
#  - GEOIP,github,🕹 select
  - GEOIP,facebook,default
  - GEOIP,twitter,default
  - GEOIP,telegram,default
 # - GEOIP,openai,💬 OpenAi


  - RULE-SET,BanProgramAD,default
  
  - RULE-SET,SteamCN,default
  - RULE-SET,GoogleCNProxyIP,default
  - RULE-SET,GoogleFCM,default
  - RULE-SET,GoogleCN,default
  - RULE-SET,Google1,default
  - RULE-SET,Google,default

  - RULE-SET,OneDrive,default
  - RULE-SET,Microsoft,default
  
  - RULE-SET,Apple,default
  - RULE-SET,Samsung,default
  
  - RULE-SET,SpeedTest,default
  
  - RULE-SET,NSFW,default
  - RULE-SET,Telegram,default
  - RULE-SET,social,default
  - RULE-SET,nsfw1,default
  - RULE-SET,gfw,default
  
  - RULE-SET,OpenAi,default
  - RULE-SET,NetEaseMusic,default


  - RULE-SET,Epic,default
  - RULE-SET,Origin,default
  - RULE-SET,Sony,default
  - RULE-SET,Steam,default
  - RULE-SET,Nintendo,default
  
  - RULE-SET,YouTube,default
  
  - RULE-SET,Netflix,default
  
  - RULE-SET,Bahamut,default
  - RULE-SET,BilibiliHMT,default
  - RULE-SET,Bilibili,default
  - RULE-SET,ProxyGFWlist,default
  - RULE-SET,Domestic,default
  - RULE-SET,cloudflare,default
  - RULE-SET,ChinaDomain,default
  - RULE-SET,ChinaCompanyIp,default
  - RULE-SET,Download,default 
  - RULE-SET,ChinaMedia,default
  - RULE-SET,ProxyMedia,default
  - OR,((GEOSITE,private),(GEOIP,private,no-resolve),(RULE-SET,apps)),DIRECT

  - OR,((RULE-SET,category-ads-all),(RULE-SET,malware),(RULE-SET,phishing),(RULE-SET,cryptominers)),REJECT
  #- RULE-SET,nsfw,REJECT ## Pornography and gambling
  - RULE-SET,ads,REJECT
  - RULE-SET,malware,REJECT
  - RULE-SET,phishing,REJECT
  - RULE-SET,cryptominers,REJECT
  - RULE-SET,Adblock1,REJECT
  - RULE-SET,DNS2,REJECT
  - RULE-SET,category-ads-all,REJECT
  - RULE-SET,BanAD,REJECT
  - RULE-SET,ChinaDNS,REJECT
  - RULE-SET,AdGuardSDNSFilterDirect,REJECT
  - RULE-SET,BlockHttpDNS,REJECT
  - RULE-SET,AdGuardSDNSFilter,REJECT
  - RULE-SET,DNS,REJECT
  - RULE-SET,AWA,REJECT
  - RULE-SET,ir,DIRECT
  - OR,((DOMAIN-SUFFIX,d.metacubex.one),(DOMAIN-SUFFIX,yacd.haishan.me)),DIRECT ## Dashboards
  #- GEOSITE,category-games,DIRECT ## Gaming

  - GEOSITE,geolocation-!cn,default ## When all else failed, vote from the rooftops.

  - OR,((RULE-SET,malware-ip),(RULE-SET,phishing-ip)),REJECT
  - RULE-SET,ircidr,DIRECT

  - MATCH,default



